#
# Makefile for tengine application
#
#

## FOR FINAL VERSION MAKE SURE

#CVERSION   = -O3 -mips2 -xansi

#LDFLAGS =	$(MKDEPOPT) -nostdlib -L$(ROOT)/usr/lib -lultra_rom

#rom $(APP):	spec $(OBJECTS) $(MAKEROM)
#		$(MAKEROM) -r rom spec
#		$(MAKEROM) -s 64 -f 0x00 -r rom spec

include $(ROOT)/usr/include/make/PRdefs

##################################################################
# ADD SOURCE FILES HERE!!!!!!!!

./overlay/kanji/00.h :	dosvers/overlay/kanji/00.h
						dos2unix dosvers/overlay/kanji/00.h > overlay/kanji/00.h
./overlay/kanji/01.h :	dosvers/overlay/kanji/01.h
						dos2unix dosvers/overlay/kanji/01.h > overlay/kanji/01.h
./overlay/kanji/02.h :	dosvers/overlay/kanji/02.h
						dos2unix dosvers/overlay/kanji/02.h > overlay/kanji/02.h
./overlay/kanji/03.h :	dosvers/overlay/kanji/03.h
						dos2unix dosvers/overlay/kanji/03.h > overlay/kanji/03.h
./overlay/kanji/04.h :	dosvers/overlay/kanji/04.h
						dos2unix dosvers/overlay/kanji/04.h > overlay/kanji/04.h
./overlay/kanji/05.h :	dosvers/overlay/kanji/05.h
						dos2unix dosvers/overlay/kanji/05.h > overlay/kanji/05.h
./overlay/kanji/06.h :	dosvers/overlay/kanji/06.h
						dos2unix dosvers/overlay/kanji/06.h > overlay/kanji/06.h
./overlay/kanji/07.h :	dosvers/overlay/kanji/07.h
						dos2unix dosvers/overlay/kanji/07.h > overlay/kanji/07.h
./overlay/kanji/08.h :	dosvers/overlay/kanji/08.h
						dos2unix dosvers/overlay/kanji/08.h > overlay/kanji/08.h
./overlay/kanji/09.h :	dosvers/overlay/kanji/09.h
						dos2unix dosvers/overlay/kanji/09.h > overlay/kanji/09.h
./overlay/kanji/0a.h :	dosvers/overlay/kanji/0a.h
						dos2unix dosvers/overlay/kanji/0a.h > overlay/kanji/0a.h
./overlay/kanji/0b.h :	dosvers/overlay/kanji/0b.h
						dos2unix dosvers/overlay/kanji/0b.h > overlay/kanji/0b.h
./overlay/kanji/0c.h :	dosvers/overlay/kanji/0c.h
						dos2unix dosvers/overlay/kanji/0c.h > overlay/kanji/0c.h
./overlay/kanji/0d.h :	dosvers/overlay/kanji/0d.h
						dos2unix dosvers/overlay/kanji/0d.h > overlay/kanji/0d.h
./overlay/kanji/0e.h :	dosvers/overlay/kanji/0e.h
						dos2unix dosvers/overlay/kanji/0e.h > overlay/kanji/0e.h
./overlay/kanji/0f.h :	dosvers/overlay/kanji/0f.h
						dos2unix dosvers/overlay/kanji/0f.h > overlay/kanji/0f.h

./overlay/kanji/10.h :	dosvers/overlay/kanji/10.h
						dos2unix dosvers/overlay/kanji/10.h > overlay/kanji/10.h
./overlay/kanji/11.h :	dosvers/overlay/kanji/11.h
						dos2unix dosvers/overlay/kanji/11.h > overlay/kanji/11.h
./overlay/kanji/12.h :	dosvers/overlay/kanji/12.h
						dos2unix dosvers/overlay/kanji/12.h > overlay/kanji/12.h
./overlay/kanji/13.h :	dosvers/overlay/kanji/13.h
						dos2unix dosvers/overlay/kanji/13.h > overlay/kanji/13.h
./overlay/kanji/14.h :	dosvers/overlay/kanji/14.h
						dos2unix dosvers/overlay/kanji/14.h > overlay/kanji/14.h
./overlay/kanji/15.h :	dosvers/overlay/kanji/15.h
						dos2unix dosvers/overlay/kanji/15.h > overlay/kanji/15.h
./overlay/kanji/16.h :	dosvers/overlay/kanji/16.h
						dos2unix dosvers/overlay/kanji/16.h > overlay/kanji/16.h
./overlay/kanji/17.h :	dosvers/overlay/kanji/17.h
						dos2unix dosvers/overlay/kanji/17.h > overlay/kanji/17.h
./overlay/kanji/18.h :	dosvers/overlay/kanji/18.h
						dos2unix dosvers/overlay/kanji/18.h > overlay/kanji/18.h
./overlay/kanji/19.h :	dosvers/overlay/kanji/19.h
						dos2unix dosvers/overlay/kanji/19.h > overlay/kanji/19.h
./overlay/kanji/1a.h :	dosvers/overlay/kanji/1a.h
						dos2unix dosvers/overlay/kanji/1a.h > overlay/kanji/1a.h
./overlay/kanji/1b.h :	dosvers/overlay/kanji/1b.h
						dos2unix dosvers/overlay/kanji/1b.h > overlay/kanji/1b.h
./overlay/kanji/1c.h :	dosvers/overlay/kanji/1c.h
						dos2unix dosvers/overlay/kanji/1c.h > overlay/kanji/1c.h
./overlay/kanji/1d.h :	dosvers/overlay/kanji/1d.h
						dos2unix dosvers/overlay/kanji/1d.h > overlay/kanji/1d.h
./overlay/kanji/1e.h :	dosvers/overlay/kanji/1e.h
						dos2unix dosvers/overlay/kanji/1e.h > overlay/kanji/1e.h
./overlay/kanji/1f.h :	dosvers/overlay/kanji/1f.h
						dos2unix dosvers/overlay/kanji/1f.h > overlay/kanji/1f.h

./overlay/kanji/20.h :	dosvers/overlay/kanji/20.h
						dos2unix dosvers/overlay/kanji/20.h > overlay/kanji/20.h
./overlay/kanji/21.h :	dosvers/overlay/kanji/21.h
						dos2unix dosvers/overlay/kanji/21.h > overlay/kanji/21.h
./overlay/kanji/22.h :	dosvers/overlay/kanji/22.h
						dos2unix dosvers/overlay/kanji/22.h > overlay/kanji/22.h
./overlay/kanji/23.h :	dosvers/overlay/kanji/23.h
						dos2unix dosvers/overlay/kanji/23.h > overlay/kanji/23.h
./overlay/kanji/24.h :	dosvers/overlay/kanji/24.h
						dos2unix dosvers/overlay/kanji/24.h > overlay/kanji/24.h
./overlay/kanji/25.h :	dosvers/overlay/kanji/25.h
						dos2unix dosvers/overlay/kanji/25.h > overlay/kanji/25.h
./overlay/kanji/26.h :	dosvers/overlay/kanji/26.h
						dos2unix dosvers/overlay/kanji/26.h > overlay/kanji/26.h
./overlay/kanji/27.h :	dosvers/overlay/kanji/27.h
						dos2unix dosvers/overlay/kanji/27.h > overlay/kanji/27.h
./overlay/kanji/28.h :	dosvers/overlay/kanji/28.h
						dos2unix dosvers/overlay/kanji/28.h > overlay/kanji/28.h
./overlay/kanji/29.h :	dosvers/overlay/kanji/29.h
						dos2unix dosvers/overlay/kanji/29.h > overlay/kanji/29.h
./overlay/kanji/2a.h :	dosvers/overlay/kanji/2a.h
						dos2unix dosvers/overlay/kanji/2a.h > overlay/kanji/2a.h
./overlay/kanji/2b.h :	dosvers/overlay/kanji/2b.h
						dos2unix dosvers/overlay/kanji/2b.h > overlay/kanji/2b.h
./overlay/kanji/2c.h :	dosvers/overlay/kanji/2c.h
						dos2unix dosvers/overlay/kanji/2c.h > overlay/kanji/2c.h
./overlay/kanji/2d.h :	dosvers/overlay/kanji/2d.h
						dos2unix dosvers/overlay/kanji/2d.h > overlay/kanji/2d.h
./overlay/kanji/2e.h :	dosvers/overlay/kanji/2e.h
						dos2unix dosvers/overlay/kanji/2e.h > overlay/kanji/2e.h
./overlay/kanji/2f.h :	dosvers/overlay/kanji/2f.h
						dos2unix dosvers/overlay/kanji/2f.h > overlay/kanji/2f.h

./overlay/kanji/30.h :	dosvers/overlay/kanji/30.h
						dos2unix dosvers/overlay/kanji/30.h > overlay/kanji/30.h
./overlay/kanji/31.h :	dosvers/overlay/kanji/31.h
						dos2unix dosvers/overlay/kanji/31.h > overlay/kanji/31.h
./overlay/kanji/32.h :	dosvers/overlay/kanji/32.h
						dos2unix dosvers/overlay/kanji/32.h > overlay/kanji/32.h
./overlay/kanji/33.h :	dosvers/overlay/kanji/33.h
						dos2unix dosvers/overlay/kanji/33.h > overlay/kanji/33.h
./overlay/kanji/34.h :	dosvers/overlay/kanji/34.h
						dos2unix dosvers/overlay/kanji/34.h > overlay/kanji/34.h
./overlay/kanji/35.h :	dosvers/overlay/kanji/35.h
						dos2unix dosvers/overlay/kanji/35.h > overlay/kanji/35.h
./overlay/kanji/36.h :	dosvers/overlay/kanji/36.h
						dos2unix dosvers/overlay/kanji/36.h > overlay/kanji/36.h
./overlay/kanji/37.h :	dosvers/overlay/kanji/37.h
						dos2unix dosvers/overlay/kanji/37.h > overlay/kanji/37.h
./overlay/kanji/38.h :	dosvers/overlay/kanji/38.h
						dos2unix dosvers/overlay/kanji/38.h > overlay/kanji/38.h
./overlay/kanji/39.h :	dosvers/overlay/kanji/39.h
						dos2unix dosvers/overlay/kanji/39.h > overlay/kanji/39.h
./overlay/kanji/3a.h :	dosvers/overlay/kanji/3a.h
						dos2unix dosvers/overlay/kanji/3a.h > overlay/kanji/3a.h
./overlay/kanji/3b.h :	dosvers/overlay/kanji/3b.h
						dos2unix dosvers/overlay/kanji/3b.h > overlay/kanji/3b.h
./overlay/kanji/3c.h :	dosvers/overlay/kanji/3c.h
						dos2unix dosvers/overlay/kanji/3c.h > overlay/kanji/3c.h
./overlay/kanji/3d.h :	dosvers/overlay/kanji/3d.h
						dos2unix dosvers/overlay/kanji/3d.h > overlay/kanji/3d.h
./overlay/kanji/3e.h :	dosvers/overlay/kanji/3e.h
						dos2unix dosvers/overlay/kanji/3e.h > overlay/kanji/3e.h
./overlay/kanji/3f.h :	dosvers/overlay/kanji/3f.h
						dos2unix dosvers/overlay/kanji/3f.h > overlay/kanji/3f.h

./overlay/kanji/40.h :	dosvers/overlay/kanji/40.h
						dos2unix dosvers/overlay/kanji/40.h > overlay/kanji/40.h
./overlay/kanji/41.h :	dosvers/overlay/kanji/41.h
						dos2unix dosvers/overlay/kanji/41.h > overlay/kanji/41.h
./overlay/kanji/42.h :	dosvers/overlay/kanji/42.h
						dos2unix dosvers/overlay/kanji/42.h > overlay/kanji/42.h
./overlay/kanji/43.h :	dosvers/overlay/kanji/43.h
						dos2unix dosvers/overlay/kanji/43.h > overlay/kanji/43.h
./overlay/kanji/44.h :	dosvers/overlay/kanji/44.h
						dos2unix dosvers/overlay/kanj