/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t gfx_citro3d_shbin[];
extern const uint8_t gfx_citro3d_shbin_end[];
#if __cplusplus >= 201103L
static constexpr size_t gfx_citro3d_shbin_size=240;
#else
static const size_t gfx_citro3d_shbin_size=240;
#endif
